<?php echo $this->doctype();?>

<html>
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle('Sochimon')->setSeparator(' - ')->setAutoEscape(false) ?>
		
		<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
		
	
		
	</head>
	<body>
		<div id="content-wrap">
			<div id="inner-content-wrap">
				<h2><?php echo $this->message ?></h2>

<?php if (isset($this->reason) && $this->reason): ?>
	<p>
		<?php
		switch ($this->reason)
		{
			case 'error-controller-cannot-dispatch' :
				echo 'The requested controller was unable to dispatch the request.';
			break;
			case 'error-controller-not-found' :
				echo 'The requested controller could not be mapped to an existing controller class.';
			break;
			case 'error-controller-invalid' :
				echo 'The requested controller was not dispatchable.';
			break;
			case 'error-router-no-match' :
				echo 'The requested URL could not be matched by routing.';
			break;
			default :
				echo 'We cannot determine at this time why an error was generated.';
			break;
		}
		?>
	</p>
<?php endif ?>

<?php if (isset($this->controller) && $this->controller): ?>
	<dl>
		<dt>Controller:</dt>
		<dd><?php echo $this->escapeHtml($this->controller) ?>
			<?php
				if (isset($this->controller_class) && $this->controller_class && $this->controller_class != $this->controller)
					echo '(' . sprintf('resolves to %s', $this->escapeHtml($this->controller_class)) . ')';
			?>
		</dd>
	</dl>
<?php endif ?>

<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>
	<?php if(isset($this->exception) && $this->exception instanceof Exception): ?>
	<hr />
	<h2>Additional Information</h2>
	<h3><?php echo get_class($this->exception); ?></h3>
	<dl>
		<dt>File:</dt>
		<dd>
			<pre class="prettyprint linenums"><?php echo $this->exception->getFile() ?>:<?php echo $this->exception->getLine() ?></pre>
		</dd>
		<dt>Message:</dt>
		<dd>
			<pre class="prettyprint linenums"><?php echo $this->exception->getMessage() ?></pre>
		</dd>
		<dt>Stack Trace:</dt>
		<dd>
			<pre class="prettyprint linenums"><?php echo $this->exception->getTraceAsString() ?></pre>
		</dd>
	</dl>
	<?php
	$e = $this->exception->getPrevious();
		if ($e) :
		?>
		<hr />
		<h2>Previous Exceptions:</h2>
		<ul class="unstyled">
			<?php while($e) : ?>
			<li>
				<h3><?php echo get_class($e); ?></h3>
				<dl>
					<dt>File:</dt>
					<dd>
						<pre class="prettyprint linenums"><?php echo $e->getFile() ?>:<?php echo $e->getLine() ?></pre>
					</dd>
					<dt>Message:</dt>
					<dd>
						<pre class="prettyprint linenums"><?php echo $e->getMessage() ?></pre>
					</dd>
					<dt>Stack Trace:</dt>
					<dd>
						<pre class="prettyprint linenums"><?php echo $e->getTraceAsString() ?></pre>
					</dd>
				</dl>
			</li>
		    <?php
		        $e = $e->getPrevious();
		        endwhile;
		    ?>
		</ul>
		<?php endif; ?>
	<?php else: ?>
		<h3>No Exception Information Available</h3>
	<?php endif ?>
<?php endif ?>
			</div>
		</div>
	</body>
</html>