<?php echo $this->doctype();?>

<html>
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle('Sochimon')->setSeparator(' - ')->setAutoEscape(false) ?>
		
		<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
	
 		<link href="/css/bootstrap.min.css" rel="stylesheet" media="screen">
 		<script src="/js/jquery.js"></script>
		<script src="/js/bootstrap.min.js"></script>
		
	</head>
	<body>
		<div id="content-wrap">
			<div id="inner-content-wrap">
			
				<?php echo $this->content;?>
			</div>
		</div>
	</body>
</html>