<?php echo $this->doctype();?>

<html>
<head>
	<meta charset="utf-8">
	<?php echo $this->headTitle('Sochimon')->setSeparator(' - ')->setAutoEscape(false) ?>
	<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
	
	<link href="/css/bootstrap.min.css" rel="stylesheet" media="screen">
	<script src="/js/jquery.js"></script>
	<script src="/js/bootstrap.min.js"></script>

</head>
<body>
	<div class="navbar navbar-inverse">
		<div class="navbar-inner">
			<a class="brand" href="/">Sochimon</a>
			
		</div>
	</div>
	<div class="row-fluid">
		<div class="span2">
			<h2>Countries</h2>
			<?php //echo $this->renderCountries([]);?>
		</div>
		<div class="span2">
			<h2>Route</h2>

		</div>
		<div class="span8">
			<h2>Map</h2>
				<?php echo $this->content;?>
				
				
		</div>
	</div>
</body>
</html>