<img src="img/sochimon.png"/>
<div id="splash">



	<div class="well">
	<h1>Sochimon: Gotta Catch 'em All!</h1>
				<hr/>
		<div class="row-fluid">
			<div class="span6">

				<p>In this <strong>game</strong>, you're collecting up all of the medals from Sochi Olympics Winners.</p>
				<p>As a PHP developer, naturally you have a private jet at your disposal, making you the ideal person for the job!</p>
				<h2>Your Task</h2>
				<ol>
					<li>You will gain points for every medal you pick up.</li>
					<li>Unfortunately, the athletes also want to come along for a ride, so you have to bring them with you.</li>
					<li>Athletes will weigh down your jet, so you have to spend some of your points on fuel!</li>
					<li>You can fly wherever route you want, but you must collect all the medals</li>
				</ol>
				<h2>The Aim</h2>
				<strong>Score more points than anyone else by choosing the best route!</strong>

			</div>
			<div class="span6">
			<p><a href="/game" class="btn btn-success btn-large">Play the game!</a></p>
			<p><a href="https://twitter.com/switchsystems/" class="btn btn-info " target="_blank">Follow us on Twitter!</a></p>
			</div>
		</div>

	</div>

</div>